# -*- coding: utf-8 -*-
"""Day 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QQJxRkkGm4p4sZWhAXjIi-r9uuIxewWq
"""

x = int(input('Enter x value: '))      
y = int(input('Enter Y value: ')) 


print(x ^ y)